# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.DSSharedServices-SageMaker-DetectiveControl-02c49110ecaf:
resource "aws_iam_role" "DSSharedServices-SageMaker-DetectiveControl-02c49110ecaf" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "lambda.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  managed_policy_arns = [
    "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
  ]
  max_session_duration = 3600
  name                 = "DSSharedServices-SageMaker-DetectiveControl-02c49110ecaf"
  path                 = "/"
  tags                 = {}
  tags_all             = {}

  inline_policy {
    name = "LambdaInlineForSageMaker"
    policy = jsonencode(
      {
        Statement = [
          {
            Action = [
              "sagemaker:DeleteTags",
              "sagemaker:DeleteEndpointConfig",
              "sagemaker:ListTags",
              "sagemaker:ListTransformJobs",
              "sagemaker:StopTrainingJob",
              "sagemaker:DeleteModel",
              "sagemaker:ListTrainingJobs",
              "sagemaker:ListHyperParameterTuningJobs",
              "sagemaker:DeleteEndpoint",
              "sagemaker:ListModels",
              "sagemaker:StopTransformJob",
              "sagemaker:AddTags",
              "sagemaker:ListEndpoints",
            ]
            Effect   = "Allow"
            Resource = "*"
            Sid      = "VisualEditor0"
          },
        ]
        Version = "2012-10-17"
      }
    )
  }
}
