# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-0df410c038106cda9:
resource "aws_subnet" "subnet-0df410c038106cda9" {
  assign_ipv6_address_on_creation = false
  availability_zone               = format("%sc", data.aws_region.current.name)
  cidr_block                      = "10.2.3.0/24"
  map_public_ip_on_launch         = false
  tags = {
    "Name" = "ds-subnet-c-DSSharedServices"
  }
  tags_all = {
    "Name" = "ds-subnet-c-DSSharedServices"
  }
  vpc_id = aws_vpc.vpc-02dd2936ab232ef7e.id

  timeouts {}
}
