# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_kms_key.k_f5aba863-306d-4bad-8f9a-6486722726a6:
resource "aws_kms_key" "k_f5aba863-306d-4bad-8f9a-6486722726a6" {
  customer_master_key_spec = "SYMMETRIC_DEFAULT"
  description              = "Generated KMS Key for Sagemaker Studio's EFS encryption"
  enable_key_rotation      = true
  is_enabled               = true
  key_usage                = "ENCRYPT_DECRYPT"
  multi_region             = false
  policy = jsonencode(
    {
      Id = "KmsKey-EfsSagemakerStudioKey"
      Statement = [
        {
          Action = "kms:*"
          Effect = "Allow"
          Principal = {
            AWS = format("arn:aws:iam::%s:root",data.aws_caller_identity.current.account_id)
          }
          Resource = "*"
          Sid      = "Enable IAM User Permissions"
        },
        {
          Action = [
            "kms:Create*",
            "kms:Describe*",
            "kms:Enable*",
            "kms:List*",
            "kms:Put*",
            "kms:Update*",
            "kms:Revoke*",
            "kms:Disable*",
            "kms:Get*",
            "kms:Delete*",
            "kms:TagResource",
            "kms:UntagResource",
            "kms:ScheduleKeyDeletion",
            "kms:CancelKeyDeletion",
          ]
          Effect = "Allow"
          Principal = {
            AWS = aws_iam_role.DSSharedServices-DataScienceAdministrator-068c43b7c593.arn
          }
          Resource = "*"
          Sid      = "Allow access for Key Administrators"
        },
        {
          Action = [
            "kms:Encrypt",
            "kms:Decrypt",
            "kms:CreateGrant",
            "kms:ReEncrypt",
            "kms:GenerateDataKey",
            "kms:DescribeKey",
          ]
          Condition = {
            StringNotEquals = {
              "aws:SourceVpce" = "vpce-0393e175e43e5e2b4"
            }
          }
          Effect = "Allow"
          Principal = {
            AWS = format("arn:aws:iam::%s:root",data.aws_caller_identity.current.account_id)
          }
          Resource = "*"
          Sid      = "Allow access for Key Users"
        },
      ]
      Version = "2012-10-17"
    }
  )
  tags = {
    "StackSetName"     = "DSSharedServices"
    "StudioDomainName" = "ds-studio-domain"
  }
  tags_all = {
    "StackSetName"     = "DSSharedServices"
    "StudioDomainName" = "ds-studio-domain"
  }
}
