# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy.DSSharedServices-DataScienceAdministrator-068c43b7c593__SageMakerAccessInlinePolicy:
resource "aws_iam_role_policy" "DSSharedServices-DataScienceAdministrator-068c43b7c593__SageMakerAccessInlinePolicy" {
  name = "SageMakerAccessInlinePolicy"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "sagemaker:*",
            "iam:TagRole",
            "kms:CreateGrant",
            "kms:DescribeKey",
          ]
          Effect   = "Allow"
          Resource = "*"
          Sid      = "SageMakerDSAdminAccess"
        },
        {
          Action = [
            "iam:PassRole",
          ]
          Condition = {
            StringEquals = {
              "iam:PassedToService" = [
                "sagemaker.amazonaws.com",
              ]
            }
          }
          Effect   = "Allow"
          Resource = "*"
          Sid      = "SageMakerIamPassRole"
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.DSSharedServices-DataScienceAdministrator-068c43b7c593.id
}
