# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.DSSharedServices-DataScienceAdministrator-068c43b7c593:
resource "aws_iam_role" "DSSharedServices-DataScienceAdministrator-068c43b7c593" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            AWS = format("arn:aws:iam::%s:root", data.aws_caller_identity.current.account_id)
          }
        },
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "sagemaker.amazonaws.com"
          }
          Sid = "SageMakerTrustRelantionship"
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  managed_policy_arns = [
    "arn:aws:iam::aws:policy/AWSCloudFormationFullAccess",
    "arn:aws:iam::aws:policy/AWSCodeArtifactAdminAccess",
    "arn:aws:iam::aws:policy/AWSCodeCommitFullAccess",
    "arn:aws:iam::aws:policy/AWSKeyManagementServicePowerUser",
    "arn:aws:iam::aws:policy/AWSServiceCatalogAdminFullAccess",
    "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess",
    "arn:aws:iam::aws:policy/AmazonS3FullAccess",
    "arn:aws:iam::aws:policy/AmazonSSMFullAccess",
    "arn:aws:iam::aws:policy/ReadOnlyAccess",
  ]
  max_session_duration = 3600
  name                 = "DSSharedServices-DataScienceAdministrator-068c43b7c593"
  path                 = "/"
  tags                 = {}
  tags_all             = {}

  inline_policy {
    name = "SageMakerAccessInlinePolicy"
    policy = jsonencode(
      {
        Statement = [
          {
            Action = [
              "sagemaker:*",
              "iam:TagRole",
              "kms:CreateGrant",
              "kms:DescribeKey",
            ]
            Effect   = "Allow"
            Resource = "*"
            Sid      = "SageMakerDSAdminAccess"
          },
          {
            Action = [
              "iam:PassRole",
            ]
            Condition = {
              StringEquals = {
                "iam:PassedToService" = [
                  "sagemaker.amazonaws.com",
                ]
              }
            }
            Effect   = "Allow"
            Resource = "*"
            Sid      = "SageMakerIamPassRole"
          },
        ]
        Version = "2012-10-17"
      }
    )
  }
}
