# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-02fc8b58ffb52ffb0:
resource "aws_security_group" "sg-02fc8b58ffb52ffb0" {
  description = "Security Group for SageMaker Studio Notebook, Training Job and Hosting Endpoint"
  tags = {
    "Name" = "ds-sagemaker-vpc-sg-DSSharedServices"
  }
  tags_all = {
    "Name" = "ds-sagemaker-vpc-sg-DSSharedServices"
  }
  vpc_id = aws_vpc.vpc-02dd2936ab232ef7e.id

  timeouts {}
}
