# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_kms_alias.alias_ds-sagemaker-studio-kms:
resource "aws_kms_alias" "alias_ds-sagemaker-studio-kms" {
  name          = "alias/ds-sagemaker-studio-kms"
  target_key_id = aws_kms_key.k_f5aba863-306d-4bad-8f9a-6486722726a6.id
}
