# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-0df410c038106cda9__rtbassoc-06bcaaed321df4452:
resource "aws_route_table_association" "subnet-0df410c038106cda9__rtbassoc-06bcaaed321df4452" {
  route_table_id = aws_route_table.rtb-03041a7bb551a299c.id
  subnet_id      = aws_subnet.subnet-0df410c038106cda9.id
}
