# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_cloudwatch_event_rule.default__SageMakerVPCEnforcementRule:
resource "aws_cloudwatch_event_rule" "default__SageMakerVPCEnforcementRule" {
  description    = "The Cloudwatch Rule checking VPC enablement of SageMaker resources"
  event_bus_name = "default"
  event_pattern = jsonencode(
    {
      detail = {
        eventName = [
          "CreateTrainingJob",
          "CreateModel",
        ]
        eventSource = [
          "sagemaker.amazonaws.com",
        ]
      }
      detail-type = [
        "AWS API Call via CloudTrail",
      ]
      source = [
        "aws.sagemaker",
      ]
    }
  )
  is_enabled = true
  name       = "SageMakerVPCEnforcementRule"
  tags       = {}
  tags_all   = {}
}
