# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_codeartifact_domain.ds-domain:
resource "aws_codeartifact_domain" "ds-domain" {
  domain   = "ds-domain"
  tags     = {}
  tags_all = {}
}
