# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ssm_parameter.ds-sagemaker-vpc-sg-DSSharedServices-id:
resource "aws_ssm_parameter" "ds-sagemaker-vpc-sg-DSSharedServices-id" {
  data_type   = "text"
  description = "SageMaker Security Group ID"
  name        = "ds-sagemaker-vpc-sg-DSSharedServices-id"
  tags = {
    "Name" = "ds-vpc-DSSharedServices"
  }
  tags_all = {
    "Name" = "ds-vpc-DSSharedServices"
  }
  tier  = "Standard"
  type  = "String"
  value = aws_security_group.sg-02fc8b58ffb52ffb0.id
}
