# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-05a180294ca109595:
resource "aws_subnet" "subnet-05a180294ca109595" {
  assign_ipv6_address_on_creation = false
 
  availability_zone               = format("%sb",data.aws_region.current.name)
  cidr_block                      = "10.2.2.0/24"
  map_public_ip_on_launch         = false
  tags = {
    "Name" = "ds-subnet-b-DSSharedServices"
  }
  tags_all = {
    "Name" = "ds-subnet-b-DSSharedServices"
  }
  vpc_id = aws_vpc.vpc-02dd2936ab232ef7e.id

  timeouts {}
}
