# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ssm_parameter.ds-codeartifact-domain-name:
resource "aws_ssm_parameter" "ds-codeartifact-domain-name" {
  data_type   = "text"
  description = "Data Science CodeArtifact Domain Name"
  name        = "ds-codeartifact-domain-name"
  tags        = {}
  tags_all    = {}
  tier        = "Standard"
  type        = "String"
  value       = aws_codeartifact_domain.ds-domain.domain
}
