# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ssm_parameter.ds-codeartifact-domain-owner:
resource "aws_ssm_parameter" "ds-codeartifact-domain-owner" {
  data_type   = "text"
  description = "Data Science CodeArtifact Domain Owner i.e. the AWS Account"
  name        = "ds-codeartifact-domain-owner"
  tags        = {}
  tags_all    = {}
  tier        = "Standard"
  type        = "String"
  value       = aws_codeartifact_domain.ds-domain.owner
}
