# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ssm_parameter.ds-s3-data-lake-kms-cmk-DSSharedServices-arn:
resource "aws_ssm_parameter" "ds-sagemaker-studio-DSSharedServices-domain-id" {
  data_type   = "text"
  description = "Sagemaker Studio key arn"
  name        = "ds-sagemaker-studio-DSSharedServices-domain-id"
  tags        = {}
  tags_all    = {}
  tier        = "Standard"
  type        = "String"
  value       = aws_sagemaker_domain.d-f1ggcpwannta.id
}
