# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_kms_alias.alias_ds-s3-data-lake-kms-cmk-DSSharedServices:
resource "aws_kms_alias" "alias_ds-s3-data-lake-kms-cmk-DSSharedServices" {
  name          = "alias/ds-s3-data-lake-kms-cmk-DSSharedServices"
  target_key_id = aws_kms_key.k_d0d1a92e-0986-40d9-88b8-7ea0a160c322.id
}
