# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_s3_bucket.ds-data-lake-029e33c5a105:
resource "aws_s3_bucket" "ds-data-lake-029e33c5a105" {
  bucket        = "ds-data-lake-andyt"
  request_payer = "BucketOwner"
  tags = {
    "SharedServiceStackSetName" = "DSSharedServices"
  }
  tags_all = {
    "SharedServiceStackSetName" = "DSSharedServices"
  }

  server_side_encryption_configuration {
    rule {
      bucket_key_enabled = false

      apply_server_side_encryption_by_default {
        kms_master_key_id = aws_kms_key.k_d0d1a92e-0986-40d9-88b8-7ea0a160c322.id
        sse_algorithm     = "aws:kms"
      }
    }
  }

  versioning {
    enabled    = false
    mfa_delete = false
  }
  force_destroy = false
  acl           = "private"
  lifecycle {
    ignore_changes = [acl, force_destroy]
  }
}
