# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ssm_parameter.ds-s3-data-lake-kms-cmk-DSSharedServices-arn:
resource "aws_ssm_parameter" "ds-s3-data-lake-kms-cmk-DSSharedServices-arn" {
  data_type   = "text"
  description = "SageMakerExecRole ARN"
  name        = "ds-s3-data-lake-kms-cmk-DSSharedServices-arn"
  tags        = {}
  tags_all    = {}
  tier        = "Standard"
  type        = "String"
  value       = aws_kms_key.k_d0d1a92e-0986-40d9-88b8-7ea0a160c322.arn
}
