# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ssm_parameter.ds-codeartifact-api-dns:
resource "aws_ssm_parameter" "ds-codeartifact-api-dns" {
  data_type   = "text"
  description = "Data Science CodeArtifact Service API VPC Endpoint DNS name"
  name        = "ds-codeartifact-api-dns"
  tags = {
    "Name" = "ds-vpc-DSSharedServices"
  }
  tags_all = {
    "Name" = "ds-vpc-DSSharedServices"
  }
  tier  = "Standard"
  type  = "String"
  value=aws_vpc_endpoint.vpce-0eb1a1f119f7bfa31.dns_entry[0].dns_name
}
