# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_codeartifact_repository.ds-public-upstream-repo:
resource "aws_codeartifact_repository" "ds-public-upstream-repo" {
  description  = "Upstream repository for shared data science repository with external connection to public PyPi repository"
  domain       = aws_codeartifact_domain.ds-domain.domain
  domain_owner = data.aws_caller_identity.current.account_id
  repository   = "ds-public-upstream-repo"
  tags         = {}
  tags_all     = {}
}
