# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ssm_parameter.ds-vpc-DSSharedServices-id:
resource "aws_ssm_parameter" "ds-vpc-DSSharedServices-id" {
  data_type   = "text"
  description = "SageMaker VPC ID"
  name        = "ds-vpc-DSSharedServices-id"
  tags = {
    "Name" = "ds-vpc-DSSharedServices"
  }
  tags_all = {
    "Name" = "ds-vpc-DSSharedServices"
  }
  tier  = "Standard"
  type  = "String"
  value = aws_vpc.vpc-02dd2936ab232ef7e.id
}
