# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-0b49e7f1e576d908d:
resource "aws_security_group" "sg-0b49e7f1e576d908d" {
  description = "Allow TLS for VPC Endpoint"
  tags = {
    "Name" = "ds-vpc-https-ingress-sg-DSSharedServices"
  }
  tags_all = {
    "Name" = "ds-vpc-https-ingress-sg-DSSharedServices"
  }
  vpc_id = aws_vpc.vpc-02dd2936ab232ef7e.id

  timeouts {}
}
