# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy_attachment.sm-lambda3-LambdaExecutionRole-1CZ0D4ZWCBDIC__AmazonEC2ReadOnlyAccess:
resource "aws_iam_role_policy_attachment" "sm-lambda3-LambdaExecutionRole-1CZ0D4ZWCBDIC__AmazonEC2ReadOnlyAccess" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess"
  role       = aws_iam_role.sm-lambda3-LambdaExecutionRole-1CZ0D4ZWCBDIC.id
}
