# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_policy.sm-lambda3-LambdaExecutionPolicy-15GBJRY2URBBI:
resource "aws_iam_policy" "sm-lambda3-LambdaExecutionPolicy-15GBJRY2URBBI" {
  name = "sm-lambda3-LambdaExecutionPolicy-15GBJRY2URBBI"
  path = "/"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "logs:CreateLogGroup",
            "logs:CreateLogStream",
            "logs:PutLogEvents",
          ]
          Effect     = "Allow"
          "Resource" = "arn:aws:logs:*:*:*"
          Sid        = "CloudWatchLogsPermissions"
        },
        {
          Action = [
            "sagemaker:ListDomains",
            "sagemaker:CreateDomain",
            "sagemaker:DescribeDomain",
            "sagemaker:DeleteDomain",
            "sagemaker:UpdateDomain",
            "sagemaker:ListUserProfiles",
            "sagemaker:CreateUserProfile",
            "sagemaker:UpdateUserProfile",
            "sagemaker:DeleteUserProfile",
            "sagemaker:DescribeUserProfile",
            "sagemaker:ListApps",
            "sagemaker:CreateApp",
            "sagemaker:DescribeApp",
            "sagemaker:DeleteApp",
            "sagemaker:UpdateApp",
          ]
          Effect = "Allow"
          "Resource" = [
            "arn:aws:sagemaker:*:*:domain/*",
            "arn:aws:sagemaker:*:*:user-profile/*",
            "arn:aws:sagemaker:*:*:app/*",
          ]
          Sid = "SageMakerDomainPermission"
        },
        {
          Action = [
            "servicecatalog:AcceptPortfolioShare",
            "sagemaker:EnableSagemakerServicecatalogPortfolio",
            "sagemaker:DisableSagemakerServicecatalogPortfolio",
          ]
          Effect     = "Allow"
          "Resource" = "*"
          Sid        = "SageMakerProjectsPermission"
        },
        {
          Action = [
            "servicecatalog:*",
          ]
          Effect     = "Allow"
          "Resource" = "*"
          Sid        = "ServiceCatalogPermission"
        },
        {
          Action = [
            "iam:PassRole",
          ]
          Effect   = "Allow"
          Resource = aws_iam_role.sm-lambda3-SageMakerExecutionRole-6GK0Q5CBBTSG.arn
          Sid      = "SageMakerExecPassRole"
        },
      ]
      Version = "2012-10-17"
    }
  )
  tags     = {}
  tags_all = {}
}
