# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_cloudwatch_event_rule.default__smdomain:
resource "aws_cloudwatch_event_rule" "default__smdomain" {
  event_bus_name = "default"
  event_pattern = jsonencode(
    {
      detail = {
        eventName = [
          "CreateDomain",
        ]
        eventSource = [
          "sagemaker.amazonaws.com",
        ]
      }
      detail-type = [
        "AWS API Call via CloudTrail",
      ]
      source = [
        "aws.sagemaker",
      ]
    }
  )
  is_enabled = true
  name       = "smdomain"
  tags       = {}
  tags_all   = {}
}
