# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.sm-lambda3-LambdaExecutionRole-1CZ0D4ZWCBDIC:
resource "aws_iam_role" "sm-lambda3-LambdaExecutionRole-1CZ0D4ZWCBDIC" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "lambda.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  managed_policy_arns = [
    aws_iam_policy.sm-lambda3-LambdaExecutionPolicy-15GBJRY2URBBI.arn,
    #"arn:aws:iam::123456789012:policy/sm-lambda3-LambdaExecutionPolicy-15GBJRY2URBBI",
    "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess",
    "arn:aws:iam::aws:policy/AmazonS3FullAccess",
    "arn:aws:iam::aws:policy/IAMFullAccess",
    "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
  ]
  max_session_duration = 3600
  name                 = "sm-lambda3-LambdaExecutionRole-1CZ0D4ZWCBDIC"
  path                 = "/"
  tags                 = {}
  tags_all             = {}

  inline_policy {}
}
