# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy_attachment.sm-lambda3-LambdaExecutionRole-1CZ0D4ZWCBDIC__sm-lambda3-LambdaExecutionPolicy-15GBJRY2URBBI:
resource "aws_iam_role_policy_attachment" "sm-lambda3-LambdaExecutionRole-1CZ0D4ZWCBDIC__sm-lambda3-LambdaExecutionPolicy-15GBJRY2URBBI" {
  policy_arn = aws_iam_policy.sm-lambda3-LambdaExecutionPolicy-15GBJRY2URBBI.arn
  role       = aws_iam_role.sm-lambda3-LambdaExecutionRole-1CZ0D4ZWCBDIC.id
}
