# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ecr_repository.ds-shared-container-images:
resource "aws_ecr_repository" "ds-shared-container-images" {
  image_tag_mutability = "MUTABLE"
  name                 = "ds-shared-container-images"
  tags = {
    "SharedServiceStackSetName" = "DSSharedServices"
  }
  tags_all = {
    "SharedServiceStackSetName" = "DSSharedServices"
  }

  encryption_configuration {
    encryption_type = "KMS"
  }

  image_scanning_configuration {
    scan_on_push = true
  }

  timeouts {}
}
