# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy_attachment.sm-lambda3-LambdaExecutionRole-1CZ0D4ZWCBDIC__AWSLambdaBasicExecutionRole:
resource "aws_iam_role_policy_attachment" "sm-lambda3-LambdaExecutionRole-1CZ0D4ZWCBDIC__AWSLambdaBasicExecutionRole" {
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  role       = aws_iam_role.sm-lambda3-LambdaExecutionRole-1CZ0D4ZWCBDIC.id
}
