# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_cloudwatch_event_target.default__smdomain__Idfd688a5f-5d70-4013-95d5-67087a1d6b7a:
resource "aws_cloudwatch_event_target" "default__smdomain__Idfd688a5f-5d70-4013-95d5-67087a1d6b7a" {
  arn            = "arn:aws:logs:eu-west-2:566972129213:log-group:/aws/events/sagemaker"
  event_bus_name = "default"
  lifecycle {
    ignore_changes = [input_transformer[0].input_template]
  }
  rule      = "smdomain"
  target_id = "Idfd688a5f-5d70-4013-95d5-67087a1d6b7a"
}
