# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy.sm-lambda3-SageMakerExecutionRole-6GK0Q5CBBTSG__s3-access:
resource "aws_iam_role_policy" "sm-lambda3-SageMakerExecutionRole-6GK0Q5CBBTSG__s3-access" {
  name = "s3-access"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "s3:GetObject",
            "s3:PutObject",
            "s3:DeleteObject",
            "s3:ListBucket",
          ]
          Effect   = "Allow"
          Resource = "arn:aws:s3:::*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.sm-lambda3-SageMakerExecutionRole-6GK0Q5CBBTSG.id
}
