# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy_attachment.sm-lambda3-SageMakerExecutionRole-6GK0Q5CBBTSG__AWSCodePipeline_FullAccess:
resource "aws_iam_role_policy_attachment" "sm-lambda3-SageMakerExecutionRole-6GK0Q5CBBTSG__AWSCodePipeline_FullAccess" {
  policy_arn = "arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess"
  role       = aws_iam_role.sm-lambda3-SageMakerExecutionRole-6GK0Q5CBBTSG.id
}
