# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_cloudwatch_event_target.default__smdomain__Id135e4ccc-993b-49a8-8e80-01df9fbf0c60:
resource "aws_cloudwatch_event_target" "default__smdomain__Id135e4ccc-993b-49a8-8e80-01df9fbf0c60" {
  arn            = aws_lambda_function.CFEnableSagemakerProjects.arn
  event_bus_name = "default"
  lifecycle {
    ignore_changes = [input_transformer[0].input_template]
  }
  rule      = "smdomain"
  target_id = "Id135e4ccc-993b-49a8-8e80-01df9fbf0c60"
}
