# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lambda_function.CFEnableSagemakerProjects:
resource "aws_lambda_function" "CFEnableSagemakerProjects" {
  architectures = [
    "x86_64",
  ]
  description   = "Enable Sagemaker Projects"
  function_name = "CFEnableSagemakerProjects"
  handler       = "index.lambda_handler"
  lifecycle {
    ignore_changes = [filename]
  }
  filename                       = "CFEnableSagemakerProjects.zip"
  layers                         = []
  memory_size                    = 512
  package_type                   = "Zip"
  reserved_concurrent_executions = -1
  role                           = aws_iam_role.sm-lambda3-LambdaExecutionRole-1CZ0D4ZWCBDIC.arn
  runtime                        = "python3.7"
  source_code_hash               = filebase64sha256("CFEnableSagemakerProjects.zip")
  tags                           = {}
  tags_all                       = {}
  timeout                        = 480

  timeouts {}

  tracing_config {
    mode = "PassThrough"
  }
}
