# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy.sm-lambda3-SageMakerExecutionRole-6GK0Q5CBBTSG__iam-access:
resource "aws_iam_role_policy" "sm-lambda3-SageMakerExecutionRole-6GK0Q5CBBTSG__iam-access" {
  name = "iam-access"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "iam:GetRole",
            "iam:GetRolePolicy",
          ]
          Effect   = "Allow"
          Resource = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.sm-lambda3-SageMakerExecutionRole-6GK0Q5CBBTSG.id
}
