# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lambda_permission.AWSEvents_smdomain_Id135e4ccc-993b-49a8-8e80-01df9fbf0c60:
resource "aws_lambda_permission" "AWSEvents_smdomain_Id135e4ccc-993b-49a8-8e80-01df9fbf0c60" {
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.CFEnableSagemakerProjects.arn
  principal     = "events.amazonaws.com"
  source_arn    = format("arn:aws:events:%s:%s:rule/smdomain", data.aws_region.current.name, data.aws_caller_identity.current.account_id)
  statement_id  = "AWSEvents_smdomain_Id135e4ccc-993b-49a8-8e80-01df9fbf0c60"
}
