# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_servicecatalog_portfolio.port-ofv7uufanw5wk:
resource "aws_servicecatalog_portfolio" "port-ofv7uufanw5wk" {
  description   = "This portfolio is a collection of products designed to support managing data science teams"
  name          = "Data Science Administrator Portfolio"
  provider_name = "Cloud Operations Team"
  tags          = {}
  tags_all      = {}

  timeouts {}
}
