# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_servicecatalog_principal_portfolio_association.arn_aws_iam__123456789012_role_DSSharedServices-DataScienceAdministrator-068c43b7c593__port-ofv7uufanw5wk:
resource "aws_servicecatalog_principal_portfolio_association" "arn_aws_iam__role_DSSharedServices-DataScienceAdministrator-068c43b7c593__port-ofv7uufanw5wk" {
  accept_language = "en"
  portfolio_id    = aws_servicecatalog_portfolio.port-ofv7uufanw5wk.id
  principal_arn   = data.aws_iam_role.DSSharedServices-DataScienceAdministrator-068c43b7c593.arn
  principal_type  = "IAM"
}
