# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-025daba223195049c__rtbassoc-0ca7d1d45659de9ce:
resource "aws_route_table_association" "subnet-025daba223195049c__rtbassoc-0ca7d1d45659de9ce" {
  route_table_id = aws_route_table.rtb-03041a7bb551a299c.id
  subnet_id      = aws_subnet.subnet-025daba223195049c.id
}
