# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy_attachment.AmazonSageMakerServiceCatalogProductsLaunchRole__AmazonSageMakerAdmin-ServiceCatalogProductsServiceRolePolicy:
resource "aws_iam_role_policy_attachment" "AmazonSageMakerServiceCatalogProductsLaunchRole__AmazonSageMakerAdmin-ServiceCatalogProductsServiceRolePolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonSageMakerAdmin-ServiceCatalogProductsServiceRolePolicy"
  role       = aws_iam_role.AmazonSageMakerServiceCatalogProductsLaunchRole.id
}
