# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ssm_parameter.ds-subnet-c-DSSharedServices-id:
resource "aws_ssm_parameter" "ds-administrator-role-DSSharedServices-id" {
  data_type   = "text"
  description = "DS Admonistrator Role ARN"
  name        = "ds-administrator-role-DSSharedServices-id"
  tags = {
    "Name" = "ds-administrator-role-DSSharedServices"
  }
  tags_all = {
    "Name" = "ds-administrator-role-DSSharedServices"
  }
  tier  = "Standard"
  type  = "String"
  value = aws_iam_role.DSSharedServices-DataScienceAdministrator-068c43b7c593.arn
}
