# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.AmazonSageMakerServiceCatalogProductsLaunchRole:
resource "aws_iam_role" "AmazonSageMakerServiceCatalogProductsLaunchRole" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "servicecatalog.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  description           = "SageMaker role created from the SageMaker AWS Management Console. This role has the permissions required to launch the Amazon SageMaker portfolio of products from AWS ServiceCatalog."
  force_detach_policies = false
  managed_policy_arns = [
    "arn:aws:iam::aws:policy/AmazonSageMakerAdmin-ServiceCatalogProductsServiceRolePolicy",
  ]
  max_session_duration = 3600
  name                 = "AmazonSageMakerServiceCatalogProductsLaunchRole"
  path                 = "/service-role/"
  tags                 = {}
  tags_all             = {}

  inline_policy {}
}
