# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group_rule.sg-0b49e7f1e576d908d_ingress_1:
resource "aws_security_group_rule" "sg-0b49e7f1e576d908d_ingress_1" {
  from_port                = 443
  prefix_list_ids          = []
  protocol                 = "tcp"
  security_group_id        = aws_security_group.sg-0b49e7f1e576d908d.id
  source_security_group_id = aws_security_group.sg-02fc8b58ffb52ffb0.id
  to_port                  = 443
  type                     = "ingress"
}
