# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.AmazonSageMakerServiceCatalogProductsUseRole:
resource "aws_iam_role" "AmazonSageMakerServiceCatalogProductsUseRole" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = [
              "sagemaker.amazonaws.com",
              "codebuild.amazonaws.com",
              "glue.amazonaws.com",
              "states.amazonaws.com",
              "events.amazonaws.com",
              "firehose.amazonaws.com",
              "cloudformation.amazonaws.com",
              "codepipeline.amazonaws.com",
              "apigateway.amazonaws.com",
              "lambda.amazonaws.com",
            ]
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  description           = "SageMaker role created from the SageMaker AWS Management Console. This role has the permissions required to use the Amazon SageMaker portfolio of products from AWS ServiceCatalog."
  force_detach_policies = false
  managed_policy_arns = [
    "arn:aws:iam::433146468867:policy/service-role/AmazonSageMakerServiceCatalogProductsUseRole-20210927T135082",
  ]
  max_session_duration = 3600
  name                 = "AmazonSageMakerServiceCatalogProductsUseRole"
  path                 = "/service-role/"
  tags                 = {}
  tags_all             = {}

  inline_policy {}
}
