# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy_attachment.DSSharedServices-DataScienceAdministrator-068c43b7c593__AmazonS3FullAccess:
resource "aws_iam_role_policy_attachment" "DSSharedServices-DataScienceAdministrator-068c43b7c593__AmazonS3FullAccess" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonS3FullAccess"
  role       = aws_iam_role.DSSharedServices-DataScienceAdministrator-068c43b7c593.id
}
