# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-09b449dac0e751ab6:
resource "aws_security_group" "sg-09b449dac0e751ab6" {
  description = "Allow HTTP for VPC Endpoint"
  tags = {
    "Name" = "ds-vpc-http-ingress-sg-DSSharedServices"
  }
  tags_all = {
    "Name" = "ds-vpc-http-ingress-sg-DSSharedServices"
  }
  vpc_id = aws_vpc.vpc-02dd2936ab232ef7e.id

  timeouts {}
}
