# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ssm_parameter.ds-shared-ecr-repository-DSSharedService:
resource "aws_ssm_parameter" "ds-shared-ecr-repository-DSSharedService-arn" {
  data_type   = "text"
  description = "DS ECR Repo Arn"
  name        = "ds-shared-ecr-repository-DSSharedService-arn"
  tags        = {}
  tags_all    = {}
  tier        = "Standard"
  type        = "String"
  value       = data.aws_ecr_repository.ds-shared-container-images.arn
}
