# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_sagemaker_app_image_config.ds-studio-domain:
resource "aws_sagemaker_app_image_config" "ds-studio-domain" {
  app_image_config_name = "ds-studio-domain"
  tags = {
    "StackSetName"     = "DSSharedServices"
    "StudioDomainName" = "ds-studio-domain"
  }
  tags_all = {
    "StackSetName"     = "DSSharedServices"
    "StudioDomainName" = "ds-studio-domain"
  }

  kernel_gateway_image_config {
    file_system_config {
      default_gid = 100
      default_uid = 1000
      mount_path  = "/home/jovyan/work"
    }

    kernel_spec {
      display_name = "Python 3"
      name         = "python3"
    }
  }
}
