# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_sagemaker_image.ds-custom-tensorflow241:
resource "aws_sagemaker_image" "ds-custom-tensorflow241" {
  description  = "ds-tensorflow241-image-config"
  display_name = "ds-tensorflow241-image-config"
  image_name   = "ds-custom-tensorflow241"
  role_arn     = aws_iam_role.DSSharedServices-DataScienceAdministrator-068c43b7c593.arn
  tags = {
    "StackSetName"     = "DSSharedServices"
    "StudioDomainName" = "ds-studio-domain"
  }
  tags_all = {
    "StackSetName"     = "DSSharedServices"
    "StudioDomainName" = "ds-studio-domain"
  }
}
