# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_cloudwatch_event_target.default__SageMakerVPCEnforcementRule__SagemakerVPCEnforcementLambda:
resource "aws_cloudwatch_event_target" "default__SageMakerVPCEnforcementRule__SagemakerVPCEnforcementLambda" {
  arn            = aws_lambda_function.SageMakerVPCEnforcer.arn
  event_bus_name = "default"
  rule           = "SageMakerVPCEnforcementRule"
  target_id      = "SagemakerVPCEnforcementLambda"
}
